---
- name: Create config dir
  become: yes
  become_user: root
  with_items:
    - /etc/etcd/
    - /var/lib/etcd/
    - /var/lib/etcd/ETCD.BACKUP
    - /data/
    - /data/ETCD.BACKUP/

  file:
    path: "{{item}}"
    state: directory
    mode: 0755

- name: install utils pkgs
  become: yes
  become_user: root
  with_items:
    - jq
  yum:
    name: '{{item}}'
    state: latest

- name: Setup etcd service def
  become: yes
  become_user: root
  with_items:
    - etcd.service
    - etcd-status-guard.service
  copy:
    src: files/services/{{item}}
    dest: /etc/systemd/system/{{item}}
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: sync confd config
  synchronize:
    src: files/confd/
    dest: /etc/confd/
    checksum: yes
    times: no

- name: load startup script
  become: yes
  become_user: root
  with_items:
    - leave.sh
    - join.sh
    - compact.sh
    - post_run.sh
    - backup.sh
    - restore.sh
    - delete_backup.sh
  copy:
    src: files/script/{{item}}
    dest: /usr/local/bin/{{item}}
    owner: root
    group: root
    mode: 0755
    backup: yes
