---
- name: Setup etcd cluster
  hosts: all
  remote_user: root
  roles:
    - base
    - appcenter-agent
    - andrewrothstein.etcd
    - monitor

- name: Setup etcd node
  hosts: etcd_node
  remote_user: root
  roles:
    - etcd-service

- name: Setup etcd proxy node
  hosts: etcd_proxy
  remote_user: root
  roles:     
    - etcd-proxy
    - coredns