---
name: Setup AppCenter Agent
  become: yes
  become_user: root
  get_url:
    url: '{{etcd_tgz_url}}'
    dest: /tmp/{{etcd_tgz}}
    checksum: '{{etcd_checksum}}'
    timeout: '{{etcd_download_timeout_seconds}}'
    mode: 0644
