---
galaxy_info:
  author: Fan Shang Xiang
  description: installs coredns
  company: yunify
  license:
    - MIT
  min_ansible_version: 1.2
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - coredns
    - dns

dependencies:
  - role: andrewrothstein.unarchive-deps
    version: v1.0.9
